version = 0.1

[default.deploy.parameters]
stack_name = "news-pwa-backend"
resolve_s3 = true
s3_prefix = "news-pwa-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
